# Fixed ESP32-S3 desk-robot hardware configuration.
CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=y
CONFIG_ESP_CONSOLE_SECONDARY_NONE=y
CONFIG_ESP_CONSOLE_UART_BAUDRATE=115200
CONFIG_ESPTOOLPY_MONITOR_BAUD=115200
CONFIG_BOOTLOADER_LOG_LEVEL_NONE=n
CONFIG_BOOTLOADER_LOG_LEVEL_INFO=y
CONFIG_ESP_SYSTEM_PANIC_REBOOT_DELAY_SECONDS=3
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_LWIP_MAX_SOCKETS=16
CONFIG_XIAOZHI_CAMERA_ALLOW_JPEG_INPUT=y
CONFIG_CAMERA_OV3660=n
CONFIG_OV3660_SUPPORT=y
CONFIG_SCCB_HARDWARE_I2C_DRIVER_NEW=y

CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=y

CONFIG_SPIRAM=y
CONFIG_SPIRAM_SPEED_80M=y
CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=1024
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=102400
CONFIG_SPIRAM_MEMTEST=n
CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=y

CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM=3
CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM=6
CONFIG_ESP_WIFI_RX_BA_WIN=3
CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=16
CONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA=y

CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=y
CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y

CONFIG_SR_WN_WN9_HIWALLE_TTS2=y

# Keep the camera DMA bounce buffer out of internal SRAM so AFE/WakeNet10
# still has a usable internal heap after boot.
CONFIG_CAMERA_PSRAM_DMA=y

CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=4096
CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE=1536

# LVGL Graphics
CONFIG_LV_USE_SNAPSHOT=y
# Builtin TLSF pool in PSRAM (lvgl_psram_pool.h). Keep the base pool small
# enough for 2MB PSRAM boards; 8MB boards add extra pools in lcd_display.cc
# (chunked to LV_MEM_SIZE — TLSF rejects a single add_pool larger than this).
# A future no-PSRAM configuration must switch back to CLIB malloc rather than
# allocating this pool from internal DRAM.
CONFIG_LV_USE_BUILTIN_MALLOC=y
# CONFIG_LV_USE_CLIB_MALLOC is not set
CONFIG_LV_MEM_SIZE_KILOBYTES=1024
