#ifndef ESP32_S3_CAMERA_ROBOT_CONFIG_H_
#define ESP32_S3_CAMERA_ROBOT_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_MIC_IS_PDM 0

// INMP441 microphone.
#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_1
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_42

// MAX98357A/MAX98567A-compatible I2S amplifier wiring.
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_40
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_39

// TTP223 with jumper A: idle high (LED on), touched low, connected to GPIO0.
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUTTON_ACTIVE_HIGH false

// Small Edison/status LED. It originally shared GPIO14 with the optional
// WS2812 strip; the strip is omitted and the LED is driven by PWM on GPIO48.
#define BUILTIN_LED_GPIO GPIO_NUM_48
#define BUILTIN_LED_COUNT 1
#define BUILTIN_LED_OUTPUT_INVERT false
#define BUILTIN_LED_LEDC_TIMER LEDC_TIMER_2
#define BUILTIN_LED_LEDC_CHANNEL LEDC_CHANNEL_2
#define BUILTIN_LED_STATUS_PROFILE_EDISON true
#define STATUS_LIGHT_DEFAULT_BRIGHTNESS 100

// ST7789 1.5-inch IPS, 240x240, eight-pin SPI module.
#define DISPLAY_SPI_HOST SPI3_HOST
#define DISPLAY_SCLK_PIN GPIO_NUM_19
#define DISPLAY_MOSI_PIN GPIO_NUM_20
#define DISPLAY_RST_PIN GPIO_NUM_21
#define DISPLAY_DC_PIN GPIO_NUM_47
#define DISPLAY_CS_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define HAS_DISPLAY_BACKLIGHT 1
#define DISPLAY_SPI_MODE 3
#define DISPLAY_SPI_CLOCK_HZ (10 * 1000 * 1000)
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_PANEL_GAP_X 80
#define DISPLAY_PANEL_GAP_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR true

// L298N Mini: motor B is left and motor A is right in the wiring diagram.
// GPIO43/GPIO44 normally carry UART0, so this board build disables the
// application console and exposes logs through the local web UI instead.
#define MOTOR_LEFT_IN1 GPIO_NUM_43
#define MOTOR_LEFT_IN2 GPIO_NUM_44
#define MOTOR_RIGHT_IN1 GPIO_NUM_3
#define MOTOR_RIGHT_IN2 GPIO_NUM_46

// ESP32-S3-CAM DVP connector. This matches bread-compact-wifi-s3cam.
#define CAMERA_PIN_D0 GPIO_NUM_11
#define CAMERA_PIN_D1 GPIO_NUM_9
#define CAMERA_PIN_D2 GPIO_NUM_8
#define CAMERA_PIN_D3 GPIO_NUM_10
#define CAMERA_PIN_D4 GPIO_NUM_12
#define CAMERA_PIN_D5 GPIO_NUM_18
#define CAMERA_PIN_D6 GPIO_NUM_17
#define CAMERA_PIN_D7 GPIO_NUM_16
#define CAMERA_PIN_XCLK GPIO_NUM_15
#define CAMERA_PIN_PCLK GPIO_NUM_13
#define CAMERA_PIN_VSYNC GPIO_NUM_6
#define CAMERA_PIN_HREF GPIO_NUM_7
#define CAMERA_PIN_SIOC GPIO_NUM_5
#define CAMERA_PIN_SIOD GPIO_NUM_4
#define CAMERA_PIN_PWDN GPIO_NUM_NC
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define CAMERA_XCLK_FREQ_HZ 20000000
#define DESK_ROBOT_USE_ESP32_CAMERA 1

// Downward-facing VL53L0X cliff sensor sharing the camera SCCB/I2C bus.
#define DISTANCE_SENSOR_SDA_PIN GPIO_NUM_4
#define DISTANCE_SENSOR_SCL_PIN GPIO_NUM_5
#define DISTANCE_SENSOR_I2C_ADDRESS 0x29
#define CLIFF_EDGE_DISTANCE_MM 150
#define CLIFF_CONFIRM_SAMPLES 2
#define DISTANCE_SENSOR_PERIOD_MS 80

// Secondary 0.91-inch SSD1306 OLED on a dedicated I2C controller.
#define SECONDARY_OLED_SDA_PIN GPIO_NUM_38
#define SECONDARY_OLED_SCL_PIN GPIO_NUM_14
#define SECONDARY_OLED_I2C_ADDRESS 0x3C
#define SECONDARY_OLED_WIDTH 128
#define SECONDARY_OLED_HEIGHT 32
#define SECONDARY_OLED_FLIP_180 true

#endif  // ESP32_S3_CAMERA_ROBOT_CONFIG_H_
